### ISSUE TITLE
IllegalArgumentException when opening split tab fails

### ISSUE THREAD

**Issue by nazar-pc** [parallaxe/OpenInSplittedTab#8]
I'm getting following error regularly in PhpStorm 2016.2:
```
EditorWindow: files=[] is not a member of this container
java.lang.IllegalArgumentException: EditorWindow: files=[] is not a member of this container
	at com.intellij.openapi.fileEditor.impl.EditorsSplitters.a(EditorsSplitters.java:450)
	at com.intellij.openapi.fileEditor.impl.EditorsSplitters.setCurrentWindow(EditorsSplitters.java:626)
	at com.intellij.openapi.fileEditor.impl.EditorWindow.setAsCurrentWindow(EditorWindow.java:470)
	at org.para.plugin.OpenInSplittedTabAction$1.actionPerformed(OpenInSplittedTabAction.java:48)
	at javax.swing.Timer.fireActionPerformed(Timer.java:313)
	at javax.swing.Timer$DoPostEvent.run(Timer.java:245)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:756)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:76)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:726)
	at com.intellij.ide.IdeEventQueue.h(IdeEventQueue.java:863)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:699)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:385)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
```

I believe this happens in some cases when opening split tab doesn't work.

**Comment by parallaxe** [comment]
Sorry, haven't checked the notifications in github for a while. I can confirm it and will try to track it down within the next weeks.

**Comment by nazar-pc** [comment]
@parallaxe, will you have some time to work on this soon?

**Comment by parallaxe** [comment]
I've just pushed a new version that should resolve this problem. I haven't it updated in the jetbrains plugin-repository yet, as I hope that you could try the updated version for yourself and tell me if it works now.
You can update the plugin with the OpenInSplittedTab.jar-file that is inside this repository by using the "Install plugin from disk"-button in the Plugin-Preferences. I please you to also verify if https://github.com/parallaxe/OpenInSplittedTab/issues/7 is also fixed with this version.

**Comment by nazar-pc** [comment]
It does work now, but in addition to split tab it opens a window with target file and location.
This is with #7 at the same time.
You can reproduce it by clicking [here](https://github.com/nazar-pc/CleverStyle-Framework/blob/c2d4ab5877ac52b40fd3515656464b74d9ca7afc/core/functions.php#L470-L470) on `array_map_arguments_bool` function.

**Comment by parallaxe** [comment]
It opens a new window? Like, a completely new IDE-window? Either I don't understand it or I can't reproduce it locally. When I use the action on `array_map_arguments_bool`, it works as expected: it creates a vertical split, opens the same file and jumps to the definition of `array_map_arguments_bool`. 
To avoid misunderstandings, I made the following screenrecording of it:
![openinsplittedtab_phpstorm_ 8](https://cloud.githubusercontent.com/assets/1765580/19630029/75df7ee6-9982-11e6-95f0-2025a6fea8e4.gif)
I'm testing it with PhpStorm 2016.2.1 / Evaluator License on Mac OS 10.11.6. Might you please add your versions of PhpStorm / OS so that I can try to reproduce it locally?

**Comment by nazar-pc** [comment]
Yes, totally new window, like when pressing Shift+F4.

PhpStorm 2016.3 EAP (163.6512.15)
JRE: 1.8.0_112-release-b403 amd64
Ubuntu 17.04 (version under development, mostly like 16.10 at the moment)

**Comment by nazar-pc** [comment]
![ezgif-2462128942](https://cloud.githubusercontent.com/assets/928965/19630161/183fd08c-998d-11e6-979a-74a9b874870b.gif)

**Comment by parallaxe** [comment]
Uh, interesting, thanks for the GIF & informations! Going to try to track it down in a virtual machine tomorrow.

**Comment by parallaxe** [comment]
I was able to reproduce it, even on mac OS - though, only when "shift" was pressed while i performed the action. When your shortcut for the action contains the shift-key, i think the version i just pushed should fix the problem.
If not, please report back with the shortcut you are using.

**Comment by nazar-pc** [comment]
Default key to go to definition is Ctrl, so for split tab I selected Ctrl+Shift.
Latest version indeed works as expected, thank you!

**Comment by parallaxe** [comment]
Great to hear, thanks for reporting and testing!
